prompts:
  - file://../prompts/answerPrompt.md
  - file://../prompts/pathDecisionPrompt.md
  # - file://../prompts/pathsFindingPrompt.md

providers:
  - openai:gpt-4.1-mini

tests: 
  - file://tests/answerPrompt-test.yaml
  - file://tests/pathDecisionPrompt.yaml
#promptfoo eval --config ./src/S04E03/promptfoo/promptfooconfig.yaml --env-path .env
